# 00_config.R
# R configuration for ERF phylogeny and motif scripts.

suppressPackageStartupMessages({
  library(fs)
})

PROJECT_DIR <- normalizePath(getwd(), mustWork = FALSE)

METADATA_DIR <- file.path(PROJECT_DIR, "metadata")
TF_METADATA <- file.path(METADATA_DIR, "tf_list_142.tsv")
ERF_CLADE_METADATA <- file.path(METADATA_DIR, "erf_clade_annotation.tsv")
SALINITY_ERF_METADATA <- file.path(METADATA_DIR, "salinity_linked_erfs.tsv")

OUT_DIR <- file.path(PROJECT_DIR, "results", "03_erf_phylogeny_motifs")
INTERMEDIATE_DIR <- file.path(OUT_DIR, "intermediate")
LOGO_DIR <- file.path(OUT_DIR, "motif_logos")

# Inputs generated by earlier scripts in this folder.
ERF_DBD_FASTA <- file.path(OUT_DIR, "sorghum_erf_ap2_domains.fa")
ERF_DBD_ALIGNED_FASTA <- file.path(OUT_DIR, "sorghum_erf_ap2_domains_aligned.fa")
ERF_TREE_NWK <- file.path(OUT_DIR, "sorghum_erf_dbd_tree.nwk")

# Motif input directory.
MEME_DIR <- file.path(PROJECT_DIR, "results", "01_dapseq_processing", "meme")

# Optional peak summary from 01_dapseq_processing.
PEAK_SUMMARY <- file.path(PROJECT_DIR, "results", "01_dapseq_processing", "peak_count_summary.tsv")

dir_create(OUT_DIR, recurse = TRUE)
dir_create(INTERMEDIATE_DIR, recurse = TRUE)
dir_create(LOGO_DIR, recurse = TRUE)

message("PROJECT_DIR: ", PROJECT_DIR)
message("OUT_DIR: ", OUT_DIR)
